[Lection 12] [Molodchenko Veronika] Homework for lesson 12
vjmo/epam_internship_android_molodchenko pull request #5
Opened 2021-07-04 09:02 UTC by vjmo

2021-07-04 09:04 UTC, vjmo commented
![photo_2021-07-04_12-57-39](https://user-images.githubusercontent.com/46070493/124379460-e4c65700-dcbf-11eb-847b-328b65763ba0.jpg)
![photo_2021-07-04_12-57-41](https://user-images.githubusercontent.com/46070493/124379462-e7c14780-dcbf-11eb-93a2-836be2c55d24.jpg)
![photo_2021-07-04_12-57-43](https://user-images.githubusercontent.com/46070493/124379464-e98b0b00-dcbf-11eb-87b2-e1979be2aff7.jpg)

2021-07-05 08:26 UTC, dserbin96 requested changes

2021-07-05 08:26 UTC, dserbin96 commented on lection_8/app/src/main/java/com/example/epam_internship_android_molodchenko/MealListFragment.kt
> +        recyclerViewAdapterMeal.clickListener
Удали, тут ничего не происходит)

2021-07-05 08:26 UTC, dserbin96 commented on lection_8/app/src/main/java/com/example/epam_internship_android_molodchenko/MealListFragment.kt
> +        recyclerViewAdapterCategory.clickListener
тут тоже ничего не происходит) Удали

2021-07-05 08:26 UTC, dserbin96 commented on lection_8/app/src/main/java/com/example/epam_internship_android_molodchenko/CategoryViewHolder.kt
> +            //clickListener.invoke(modelCategory)
закоментированный код лучше удалять, засоряет код

2021-07-05 08:26 UTC, dserbin96 commented on lection_8/app/src/main/java/com/example/epam_internship_android_molodchenko/HostMainActivity.kt
> +        //if (savedInstanceState != null) {
тут и в остальных местах нужно удалить закоментированный код

2021-07-05 08:26 UTC, dserbin96 commented on lection_8/app/src/main/res/layout/category_item_list.xml
> +    android:padding="2dp"
в ресурсы

2021-07-05 08:26 UTC, dserbin96 commented on lection_8/app/src/main/res/layout/fragment_meal_details.xml
> +                    android:layout_marginEnd="196dp"
удали, отступ тут не нужен, тут нужно прикрепить якоря справа слева и вверху

2021-07-05 08:26 UTC, dserbin96 commented on lection_8/app/src/main/res/layout/fragment_meal_details.xml
>                      android:layout_alignBottom="@id/meat_txt"
android:layout_alignBottom в RelativeLayout используется удали

2021-07-05 08:26 UTC, dserbin96 commented on lection_8/app/src/main/res/layout/fragment_meal_details.xml
> +                    app:layout_constraintHorizontal_bias="0.072"
удали

2021-07-05 08:26 UTC, dserbin96 commented on lection_8/app/src/main/res/layout/fragment_meal_details.xml
> +                    app:layout_constraintVertical_bias="0.541" />
для чего эти выравнивания нужны?) тут думаю можно немного по другому сделать

2021-07-05 08:26 UTC, dserbin96 commented on lection_8/app/src/main/res/layout/fragment_meal_details.xml
> +                    android:layout_marginStart="16dp"
в ресурсы

2021-07-05 08:26 UTC, dserbin96 commented on lection_8/app/src/main/res/layout/fragment_meal_details.xml
> +                    android:layout_marginBottom="93dp"
четный и в ресурсы

2021-07-05 08:26 UTC, dserbin96 commented on lection_8/app/src/main/res/layout/fragment_meal_list.xml
> +            app:layout_constraintHorizontal_bias="0.0"
удали

2021-07-05 08:26 UTC, dserbin96 commented on lection_8/app/src/main/res/layout/fragment_meal_list.xml
> +            app:layout_constraintVertical_bias="0.0"
удали

2021-07-05 12:17 UTC, merged