[Lection 16] [Molodchenko Veronika] Homework for lesson 16
vjmo/epam_internship_android_molodchenko pull request #9
Opened 2021-09-07 14:59 UTC by vjmo

2021-09-07 15:01 UTC, vjmo commented
![photo_2021-09-07_17-58-49](https://user-images.githubusercontent.com/46070493/132367249-a4795270-d873-4077-86d2-cca9880e9503.jpg)

2021-09-09 20:28 UTC, dserbin96 requested changes

2021-09-09 20:28 UTC, dserbin96 commented on lection_8/app/src/main/java/com/example/epam_internship_android_molodchenko/MealListFragment.kt
> +            requireActivity().findViewById<AppCompatButton>(R.id.img_filter_icon)
Тут не нужно вызывать активити, так как активити имеет собсвенную верстку и не должно быть завязано на фрагменте. Для того чтобы достьучаться до верстки нужно обратиться к view то есть должно выглядить приметрно так
view.findViewById<AppCompatButton>(R.id.img_filter_icon).setOnClickListener{}

2021-09-09 20:28 UTC, dserbin96 commented on lection_8/app/src/main/java/com/example/epam_internship_android_molodchenko/MealListFragment.kt
>          initView()
сюда в аргумент функции можешь передавать непосредственно view для работы с ним то есть
initView(view)

2021-09-09 20:28 UTC, dserbin96 commented on lection_8/app/src/main/java/com/example/epam_internship_android_molodchenko/MealListFragment.kt
>      private fun initView() {
соответсвенно тут будет так 
private fun initView(view : View) {}

2021-09-09 20:28 UTC, dserbin96 commented on lection_8/app/src/main/java/com/example/epam_internship_android_molodchenko/MealListFragment.kt
> +                                requireActivity().findViewById<Button>(R.id.asc_filter)
view.findViewById<Button>(R.id.asc_filter)

2021-09-09 20:28 UTC, dserbin96 commented on lection_8/app/src/main/java/com/example/epam_internship_android_molodchenko/MealListFragment.kt
> +                                requireActivity().findViewById<Button>(R.id.desc_filter)
view.findViewById<Button>(R.id.desc_filter)

2021-09-09 20:28 UTC, dserbin96 commented on lection_8/app/src/main/java/com/example/epam_internship_android_molodchenko/MealListFragment.kt
> +                    requireActivity().findViewById<AppCompatButton>(R.id.btn_close_icon)
view.findViewById<AppCompatButton>(R.id.btn_close_icon)

2021-09-19 18:56 UTC, vjmo commented
![Screenshot_3](https://user-images.githubusercontent.com/46070493/133939465-42bd2c5b-3291-4020-9962-a1935d35cfe3.png)

2021-09-20 13:27 UTC, dserbin96 approved these changes

2021-09-20 13:27 UTC, dserbin96 commented on lection_8/app/src/main/java/com/example/epam_internship_android_molodchenko/FilterFragment.kt
> +            clickListener?.onItemClick(false)
тут можнор вызывать функцию dismiss() и тогда при нажатии сразу будет закрываться ботомшит

2021-09-20 13:27 UTC, dserbin96 commented on lection_8/app/src/main/java/com/example/epam_internship_android_molodchenko/FilterFragment.kt
> +            clickListener?.onItemClick(true)
аналогично

2021-09-24 17:10 UTC, merged